### PR TITLE
bug fix and features

### PR DESCRIPTION
**Pull request by justChargin**
I fixed a bug (checkout my commit i added a few comments about it) and added some cool features on ERC721RFull.sol

I tested my changes in remix with Javascript VM. ERC721RFull is not tested on injected web3 but it seems its working well. :)

### CODE REVIEW

**Comment by elie222** [comment]
Good catch around refunder refunding unlimited amounts. Will go over the rest a bit later. I think we may want to cut down the comments in the code to clean it up. Or to shorten to one liners / add your notes in the comments section of this PR

**Comment by justChargin** [comment]
> Good catch around refunder refunding unlimited amounts. Will go over the rest a bit later. I think we may want to cut down the comments in the code to clean it up. Or to shorten to one liners / add your notes in the comments section of this PR

I can make another pull request with clean code. I want to be contributer too should i do another pull request? And is ERC721RFull.sol good too? I can clean comments from it and then make a pull request again

**Comment by justChargin** [comment]
I removed extra contract (i thought you might not want to include it) and removed comments. I will make another pull request for ERC721RFull.sol if you want to include this contract to your repository too.

**Comment by elie222** [comment]
> I removed extra contract (i thought you might not want to include it) and removed comments. I will make another pull request for ERC721RFull.sol if you want to include this contract to your repository too.

hey, ofc you will be included. a new pr isnt needed but i will take a look at the other one too

**Comment by elie222** [comment]
Do you want to close this PR and we'll focus on the other one instead?

**Pull request closed without merging**
