### PR TITLE
Fix: Owner Not allow to call the refund

### PR DESCRIPTION
**Pull request by lawweiliang**
Hi @elie222 

Here is the improvements.
1. Stop the owner of the contract from calling the refund function
   * Create a Modifier function called `notOwner` and being call over refund function.
   * Testing code was added as well over test file. 
 
2. To simplify contributions, I did include a prettier config file.
   * If other developers want to contribute, they need not to change their prettier setting over their vs code.
  
 Hopes it helps.
 
 Regards,
 Liang

### CODE REVIEW

**Comment by qbig** [comment]
Correct me if I am wrong. @lawweiliang this is still vulnerable cuz owner can be transfer to someone else? https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol

**Comment by f0rmatting** [comment]
Hi @elie222 @lawweiliang 
Maybe is not enough, "refundAddress" can changed by setRefundAddress function, we should be prohibited all refundAddress call refund function.

**Comment by elie222** [comment]
> Hi @elie222 @lawweiliang Maybe is not enough, "refundAddress" can changed by setRefundAddress function, we should be prohibited all refundAddress call refund function.

But owner can still transfer to another address that isn't blacklisted. I left the same comment on your PR. 
We just merged in another fix for this issue: https://github.com/exo-digital-labs/ERC721R/pull/9. Happy to hear everyone's thoughts on i.:

**Comment by f0rmatting** [comment]
issue: https://github.com/exo-digital-labs/ERC721R/pull/9 is better.

**Comment by lawweiliang** [comment]
@qbig, you are right, owner still can transfer the ownership to other and refund it using the old address and continue to drain the fund. Hmm, let me think how to solve this. 

Condition.
1. We definitely cannot remove the ownership function because if there is any IP changed, owner need to transfer the IP to  new owner.

Suggestion
I got one solution for this. If owner want to change ownership, they cannot change it by themselves, they need majority vote by the community (more than 50% say yes). Yeah. Can?

**Comment by lawweiliang** [comment]
Refund problem was solved over #9 by adding has refunded. The token transfer problem by the owner was solved as well.
I closed this pull request.

**Pull request closed without merging**
